spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true  # Habilita o console H2
  jpa:
    hibernate:
      ddl-auto: update  # Cria/tabela as tabelas automaticamente
    show-sql: true      # Mostra as queries SQL no console
